--- #YAML:1.0
name:               Log-Dump
version:            0.11
abstract:           simple logger mainly for debugging
author:
    - Kenichi Ishigaki <ishigaki@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dump:           0
    IO::Capture:          0
    IO::File:             0
    Sub::Install:         0
    Test::Classy:         0.04
    Test::More:           0.47
    Test::UseAllModules:  0.09
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
